spring.application.name=discogs-service
application.version=@project.version@

#discogs configs
discogs.consumerKey=mIYUzlaVWkCyoxDKxRgz
discogs.consumerSecret=JEylezqFtHfpSmlTDtEYpovAAHiFtMSZ
discogs.baseUrl=https://api.discogs.com